"""added totp

Revision ID: 0ddd70536b35
Revises: c342153a2a66
Create Date: 2026-06-19 15:24:43.522454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ddd70536b35'
down_revision: Union[str, Sequence[str], None] = 'c342153a2a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('totp_enabled', sa.Boolean(), nullable=False))
    op.add_column('user_account', sa.Column('backup_codes', sa.JSON(), nullable=True))
    op.alter_column('user_account', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'date_created',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('user_account', 'backup_codes')
    op.drop_column('user_account', 'totp_enabled')
    op.drop_column('user_account', 'totp_secret')
    # ### end Alembic commands ###
