"""Added is verified

Revision ID: 4af5c2806cd6
Revises: 7aa65d0bbc5e
Create Date: 2026-06-01 15:46:57.813684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af5c2806cd6'
down_revision: Union[str, Sequence[str], None] = '7aa65d0bbc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'is_verified')
    # ### end Alembic commands ###
