"""changed datatype

Revision ID: 897d25576fd7
Revises: d618c2e95ce5
Create Date: 2026-06-03 17:34:32.070452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897d25576fd7'
down_revision: Union[str, Sequence[str], None] = 'd618c2e95ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_account', sa.Column('provider_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('social_account_provider_user_id_key'), 'social_account', type_='unique')
    op.create_unique_constraint(None, 'social_account', ['provider_id'])
    op.drop_column('social_account', 'provider_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_account', sa.Column('provider_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'social_account', type_='unique')
    op.create_unique_constraint(op.f('social_account_provider_user_id_key'), 'social_account', ['provider_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('social_account', 'provider_id')
    # ### end Alembic commands ###
