"""changed datatype

Revision ID: d618c2e95ce5
Revises: e6a9855023cd
Create Date: 2026-06-03 17:28:07.273725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd618c2e95ce5'
down_revision: Union[str, Sequence[str], None] = 'e6a9855023cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("social_account") as batch_op:
        batch_op.alter_column(
            'provider_user_id',
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=False,
        )
    with op.batch_alter_table("user_account") as batch_op:
        batch_op.alter_column(
            'password',
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account") as batch_op:
        batch_op.alter_column(
            'password',
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
    with op.batch_alter_table("social_account") as batch_op:
        batch_op.alter_column(
            'provider_user_id',
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
