"""changed datatype

Revision ID: 897d25576fd7
Revises: d618c2e95ce5
Create Date: 2026-06-03 17:34:32.070452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897d25576fd7'
down_revision: Union[str, Sequence[str], None] = 'd618c2e95ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_account', sa.Column('provider_id', sa.String(), nullable=True))
    op.execute("UPDATE social_account SET provider_id = provider_user_id")
    with op.batch_alter_table("social_account") as batch_op:
        batch_op.alter_column('provider_id', nullable=False)
        batch_op.create_unique_constraint(
            'social_account_provider_id_key', ['provider_id']
        )
        batch_op.drop_column('provider_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'social_account',
        sa.Column('provider_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.execute("UPDATE social_account SET provider_user_id = provider_id")
    with op.batch_alter_table("social_account") as batch_op:
        batch_op.drop_constraint('social_account_provider_id_key', type_='unique')
        batch_op.alter_column('provider_user_id', nullable=False)
        batch_op.create_unique_constraint(
            op.f('social_account_provider_user_id_key'), ['provider_user_id']
        )
        batch_op.drop_column('provider_id')
    # ### end Alembic commands ###
