"""added family id

Revision ID: c342153a2a66
Revises: 897d25576fd7
Create Date: 2026-06-10 17:34:08.871618

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c342153a2a66"
down_revision: Union[str, Sequence[str], None] = "897d25576fd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("refresh_tokens", sa.Column("family_id", sa.String(), nullable=True))
    op.add_column("refresh_tokens", sa.Column("user_agent", sa.String(), nullable=True))
    op.add_column("refresh_tokens", sa.Column("ip_address", sa.String(), nullable=True))
    op.add_column("refresh_tokens", sa.Column("device_name", sa.String(), nullable=True))
    op.add_column("session", sa.Column("user_agent", sa.String(), nullable=True))
    op.add_column("session", sa.Column("ip_address", sa.String(), nullable=True))
    op.add_column(
        "session", sa.Column("last_active", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("session", sa.Column("device_name", sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE refresh_tokens SET family_id = 'legacy'")
    op.execute("UPDATE refresh_tokens SET user_agent = 'unknown'")
    op.execute("UPDATE refresh_tokens SET ip_address = 'unknown'")
    op.execute("UPDATE refresh_tokens SET device_name = 'unknown'")
    op.execute("UPDATE session SET user_agent = 'unknown'")
    op.execute("UPDATE session SET ip_address = 'unknown'")
    op.execute("UPDATE session SET last_active = created_at")
    op.execute("UPDATE session SET device_name = 'unknown'")
    with op.batch_alter_table("refresh_tokens") as batch_op:
        batch_op.alter_column("family_id", nullable=False)
        batch_op.alter_column("user_agent", nullable=False)
        batch_op.alter_column("ip_address", nullable=False)
        batch_op.alter_column("device_name", nullable=False)
    with op.batch_alter_table("session") as batch_op:
        batch_op.alter_column("user_agent", nullable=True)
        batch_op.alter_column("ip_address", nullable=True)
        batch_op.alter_column("last_active", nullable=True)
        batch_op.alter_column("device_name", nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "device_name")
    op.drop_column("session", "last_active")
    op.drop_column("session", "ip_address")
    op.drop_column("session", "user_agent")
    op.drop_column("refresh_tokens", "device_name")
    op.drop_column("refresh_tokens", "ip_address")
    op.drop_column("refresh_tokens", "user_agent")
    op.drop_column("refresh_tokens", "family_id")
    # ### end Alembic commands ###
