const field = (name, label, options = {}) => ({ name, label, ...options });

export const routeCatalog = [
  {
    id: "root",
    group: "System",
    title: "API heartbeat",
    method: "GET",
    path: "/",
    summary: "Proves the FastAPI process can receive and serialize a request.",
    underHood: [
      "The browser sends a credential-free HTTP GET request through the Next.js reverse proxy.",
      "FastAPI matches the root path to the root() handler in app/main.py.",
      "The handler returns a Python dictionary, which FastAPI serializes to JSON with an HTTP 200 response.",
    ],
  },
  {
    id: "live",
    group: "System",
    title: "Liveness probe",
    method: "GET",
    path: "/health/live",
    summary: "Checks that the API process is alive without touching dependencies.",
    underHood: [
      "This lightweight HTTP probe avoids the database and Redis intentionally.",
      "A successful response proves the Python event loop, router, and serializer are responsive.",
      "Container platforms can call this route to decide whether the API process should be restarted.",
    ],
  },
  {
    id: "ready",
    group: "System",
    title: "Readiness probe",
    method: "GET",
    path: "/health/ready",
    summary: "Checks the database and Redis before accepting production traffic.",
    underHood: [
      "FastAPI executes SELECT 1 through SQLAlchemy and sends PING through the Redis client.",
      "Each dependency is reported independently so an operator can see exactly what is unavailable.",
      "The route returns HTTP 503 when either dependency fails, allowing a load balancer to stop routing traffic here.",
    ],
  },
  {
    id: "authHealth",
    group: "System",
    title: "Auth health",
    method: "GET",
    path: "/auth/health",
    summary: "Confirms that the authentication router is mounted.",
    underHood: [
      "The request enters FastAPI through the /auth router prefix.",
      "The handler returns an explicit authentication health payload rather than an ambiguous null body.",
      "This separates route registration health from the deeper database and Redis readiness probe.",
    ],
  },
  {
    id: "capabilities",
    group: "System",
    title: "Discover capabilities",
    method: "GET",
    path: "/auth/capabilities",
    summary: "Lets clients discover enabled auth features at runtime.",
    underHood: [
      "The route reads safe feature flags from server settings without exposing secrets.",
      "It reports the active JWT or session strategy, refresh-token support, TOTP, and configured OAuth providers.",
      "The Next.js UI uses this response to adapt labels and available security actions to the deployment.",
    ],
  },
  {
    id: "register",
    group: "Authentication",
    title: "Create account",
    method: "POST",
    path: "/auth/register",
    summary: "Creates a user, hashes the password, and starts a secure session.",
    fields: [
      field("username", "Username", { defaultValue: "demo_user" }),
      field("name", "Full name", { defaultValue: "Demo User" }),
      field("email", "Email", { type: "email", defaultValue: "demo@example.com" }),
      field("password", "Password", { type: "password", defaultValue: "password123" }),
    ],
    body: ["username", "name", "email", "password"],
    refreshAuth: true,
    underHood: [
      "The UI sends an HTTP POST with a JSON body; the Next.js proxy forwards it to FastAPI on port 8000.",
      "Pydantic validates the username, email format, and minimum password length before route code runs.",
      "Argon2 turns the password into a slow, salted hash; the raw password is never written to the database.",
      "SQLAlchemy inserts the user, then the selected backend creates an HTTP-only JWT/refresh-token pair or server-side session cookie.",
      "A security activity event is pushed into the user's bounded Redis timeline for the dashboard.",
    ],
  },
  {
    id: "login",
    group: "Authentication",
    title: "Password sign in",
    method: "POST",
    path: "/auth/login",
    summary: "Authenticates credentials with lockout protection and optional 2FA.",
    fields: [
      field("username", "Username", { defaultValue: "demo_user" }),
      field("password", "Password", { type: "password", defaultValue: "password123" }),
    ],
    form: ["username", "password"],
    refreshAuth: true,
    underHood: [
      "The browser sends application/x-www-form-urlencoded data because FastAPI's OAuth2PasswordRequestForm expects form fields.",
      "Redis is checked for a failed-login lockout before SQLAlchemy looks up the account.",
      "Argon2 verifies the submitted password against its stored hash using constant-time cryptographic checks.",
      "When TOTP is enabled, FastAPI returns a five-minute temporary token and waits for /auth/2fa/verify before issuing cookies.",
      "Otherwise an HTTP-only auth cookie is set and automatically accompanies later credentialed requests.",
    ],
  },
  {
    id: "logout",
    group: "Authentication",
    title: "Sign out here",
    method: "GET",
    path: "/auth/logout",
    summary: "Invalidates the current browser session.",
    refreshAuth: true,
    underHood: [
      "The browser includes its HTTP-only cookie even though JavaScript cannot read that cookie directly.",
      "The active backend authenticates the request, invalidates the current refresh token or database session, and clears cookies.",
      "Only this device is signed out; other valid devices remain active.",
    ],
  },
  {
    id: "logoutAll",
    group: "Authentication",
    title: "Sign out everywhere",
    method: "GET",
    path: "/auth/logout-all",
    summary: "Revokes every refresh token or server-side session for the user.",
    dangerous: true,
    refreshAuth: true,
    underHood: [
      "FastAPI authenticates the current cookie before accepting this account-wide action.",
      "JWT mode invalidates every refresh-token row; session mode invalidates every session row and removes Redis session keys.",
      "The current browser cookies are cleared, forcing every device to authenticate again.",
    ],
  },
  {
    id: "refresh",
    group: "Authentication",
    title: "Rotate JWT",
    method: "GET",
    path: "/auth/refresh",
    summary: "Exchanges a valid refresh cookie for a new token pair.",
    underHood: [
      "The raw refresh token arrives only in an HTTP-only cookie and is hashed before database lookup.",
      "FastAPI validates its expiry and valid flag, invalidates the old token, and creates a new token in the same family.",
      "Reuse of an already-rotated token invalidates the entire family, limiting replay attacks after token theft.",
    ],
  },
  {
    id: "sendVerification",
    group: "Email & recovery",
    title: "Send verification email",
    method: "GET",
    path: "/auth/verify-user",
    summary: "Queues a one-hour email verification link.",
    underHood: [
      "The auth cookie identifies the user; verified users are rejected to prevent redundant mail.",
      "A cryptographically random token is mapped to the user in Redis with a one-hour expiry.",
      "Celery sends the rendered email outside the HTTP request, keeping the API response fast.",
    ],
  },
  {
    id: "verifyEmail",
    group: "Email & recovery",
    title: "Consume verification token",
    method: "GET",
    path: "/auth/verify-email",
    summary: "Marks the account email as verified.",
    fields: [field("token", "Email token")],
    query: ["token"],
    underHood: [
      "The token travels in the URL query string and is looked up under a namespaced Redis key.",
      "A missing or expired key returns HTTP 400 without touching user data.",
      "A valid key updates is_verified, deletes the one-time token, commits the transaction, and records activity.",
    ],
  },
  {
    id: "magicLink",
    group: "Email & recovery",
    title: "Request magic link",
    method: "POST",
    path: "/auth/magic-link",
    summary: "Sends a passwordless, one-time sign-in link.",
    fields: [field("email", "Email", { type: "email", defaultValue: "demo@example.com" })],
    body: ["email"],
    underHood: [
      "The endpoint always returns the same generic message so attackers cannot enumerate registered emails.",
      "For an active account, Redis stores a random token for 15 minutes and Celery queues the email.",
      "The token is single-use and is deleted as soon as its verification route succeeds.",
    ],
  },
  {
    id: "magicVerify",
    group: "Email & recovery",
    title: "Consume magic link",
    method: "GET",
    path: "/auth/magic-link/verify",
    summary: "Turns a valid email token into an authenticated session.",
    fields: [field("token", "Magic-link token")],
    query: ["token"],
    refreshAuth: true,
    underHood: [
      "FastAPI exchanges the Redis token for a user id and rejects missing, expired, or inactive accounts.",
      "The token is deleted before the authentication backend issues cookies, making the link one-time use.",
      "The resulting cookie follows the same JWT or server-session policy as password login.",
    ],
  },
  {
    id: "forgotPassword",
    group: "Email & recovery",
    title: "Request password reset",
    method: "POST",
    path: "/auth/forgot-password",
    summary: "Queues a short-lived password reset link without leaking account existence.",
    fields: [field("email", "Email", { type: "email", defaultValue: "demo@example.com" })],
    body: ["email"],
    underHood: [
      "The route looks up the email but deliberately returns an identical response for known and unknown accounts.",
      "Redis rate limiting slows abuse, then stores a random reset token for 15 minutes.",
      "Celery handles email delivery while the API immediately returns a safe generic response.",
    ],
  },
  {
    id: "resetPassword",
    group: "Email & recovery",
    title: "Reset password",
    method: "POST",
    path: "/auth/reset-password",
    summary: "Consumes a reset token and stores a new Argon2 password hash.",
    fields: [
      field("token", "Reset token"),
      field("new_password", "New password", { type: "password" }),
    ],
    body: ["token", "new_password"],
    underHood: [
      "Pydantic rejects passwords shorter than eight characters before the handler executes.",
      "The one-time Redis token resolves to a user id and disappears after a successful reset.",
      "Only an Argon2 hash is persisted, and the security timeline records that recovery occurred.",
    ],
  },
  {
    id: "google",
    group: "OAuth",
    title: "Continue with Google",
    method: "GET",
    path: "/auth/google",
    summary: "Starts the Google OpenID Connect authorization flow.",
    external: true,
    underHood: [
      "The browser navigates to FastAPI, which creates OAuth state and redirects to Google's authorization server.",
      "Google authenticates and redirects to the configured callback with an authorization code.",
      "The callback validates provider data, links or creates a local account, then issues the normal auth cookie.",
    ],
  },
  {
    id: "googleCallback",
    group: "OAuth",
    title: "Google callback",
    method: "GET",
    path: "/auth/google/callback",
    summary: "Completes Google's server-side authorization-code exchange.",
    disabled: true,
    underHood: [
      "Google redirects here with an authorization code and the state value created at the start of the flow.",
      "Authlib validates state, exchanges the code for provider tokens, and reads the OpenID Connect user profile.",
      "FastAPI links the Google identity to an existing email or creates a local user and SocialAccount row.",
      "The selected auth backend sets HTTP-only cookies; this callback is provider-driven and should not be called manually.",
    ],
  },
  {
    id: "github",
    group: "OAuth",
    title: "Continue with GitHub",
    method: "GET",
    path: "/auth/github",
    summary: "Starts GitHub's OAuth authorization-code flow.",
    external: true,
    underHood: [
      "FastAPI redirects the browser to GitHub with a state value that protects the callback from request forgery.",
      "The callback exchanges the code for an access token and retrieves the user's primary email when necessary.",
      "A SocialAccount row links the provider identity to a local user before the standard auth cookie is issued.",
    ],
  },
  {
    id: "githubCallback",
    group: "OAuth",
    title: "GitHub callback",
    method: "GET",
    path: "/auth/github/callback",
    summary: "Completes GitHub's server-side authorization-code exchange.",
    disabled: true,
    underHood: [
      "GitHub redirects here with a short-lived code after the user approves the requested identity scope.",
      "Authlib exchanges the code, fetches the GitHub profile, and requests the primary email when it is not public.",
      "The provider id is linked through SocialAccount so future GitHub sign-ins resolve to the same local user.",
      "The standard JWT or session cookie is issued; this callback is executed by GitHub rather than the workbench.",
    ],
  },
  {
    id: "me",
    group: "Account",
    title: "Current profile",
    method: "GET",
    path: "/users/me",
    summary: "Resolves the HTTP-only cookie into the current safe user profile.",
    underHood: [
      "The auth dependency selects JWT verification or Redis-backed session lookup from server configuration.",
      "The authenticated user is loaded through SQLAlchemy and inactive accounts are rejected.",
      "Pydantic returns only approved profile fields; password hashes and TOTP secrets never leave the server.",
    ],
  },
  {
    id: "overview",
    group: "Account",
    title: "Account overview",
    method: "GET",
    path: "/users/me/overview",
    summary: "Aggregates profile, security score, providers, and active session count.",
    underHood: [
      "One credentialed request joins several safe account signals needed by the dashboard.",
      "SQLAlchemy counts valid, unexpired sessions and selects connected OAuth provider names.",
      "The backend calculates a transparent security score from email, 2FA, password, session, and recovery checks.",
    ],
  },
  {
    id: "updateMe",
    group: "Account",
    title: "Update profile",
    method: "PATCH",
    path: "/users/update-me",
    summary: "Partially updates only the submitted profile fields.",
    fields: [field("username", "Username"), field("name", "Full name"), field("email", "Email", { type: "email" })],
    body: ["username", "name", "email"],
    omitEmpty: true,
    refreshAuth: true,
    underHood: [
      "The PATCH request sends only non-empty fields and Pydantic validates each supplied value.",
      "SQLAlchemy emits a targeted UPDATE; unique constraints protect usernames and emails from collisions.",
      "The transaction is rolled back on conflict and a profile.updated activity event names the changed fields.",
    ],
  },
  {
    id: "activity",
    group: "Account",
    title: "Security activity",
    method: "GET",
    path: "/users/me/activity",
    summary: "Returns the most recent security-sensitive account actions.",
    fields: [field("limit", "Result limit", { type: "number", defaultValue: "20" })],
    query: ["limit"],
    underHood: [
      "Events are stored in a user-specific Redis list, newest first, and bounded to the latest 50 entries.",
      "The query limit is validated between 1 and 50 to control response size.",
      "Redis failures degrade to an empty timeline instead of preventing the user from accessing their account.",
    ],
  },
  {
    id: "export",
    group: "Account",
    title: "Export account",
    method: "GET",
    path: "/users/me/export",
    summary: "Generates a portable snapshot without credentials or secrets.",
    underHood: [
      "FastAPI assembles profile fields, security configuration, provider names, and active session count.",
      "Password hashes, token values, backup-code hashes, and TOTP secrets are intentionally excluded.",
      "The UI can download the JSON response locally without creating a persistent export file on the server.",
    ],
  },
  {
    id: "deleteMe",
    group: "Account",
    title: "Deactivate account",
    method: "DELETE",
    path: "/users/me/delete",
    summary: "Soft-deletes the account and revokes authentication.",
    dangerous: true,
    refreshAuth: true,
    underHood: [
      "The request must authenticate before the backend will mutate account state.",
      "The backend marks the user inactive, invalidates sessions or refresh tokens, and clears browser cookies.",
      "Soft deletion preserves relational integrity while every future authentication attempt is rejected.",
    ],
  },
  {
    id: "sessions",
    group: "Sessions",
    title: "List active devices",
    method: "GET",
    path: "/users/me/sessions",
    summary: "Normalizes active JWT refresh tokens or server sessions into one device model.",
    underHood: [
      "SQLAlchemy filters to valid, unexpired records owned by the authenticated user.",
      "JWT and session rows are normalized to the same response shape with device, IP, expiry, and current-device status.",
      "A stable opaque id lets the UI revoke a chosen session without exposing a usable raw token.",
    ],
  },
  {
    id: "revokeSession",
    group: "Sessions",
    title: "Revoke one device",
    method: "DELETE",
    path: "/users/me/sessions/{id}",
    summary: "Invalidates a selected session that belongs to the current user.",
    fields: [field("id", "Session id")],
    params: ["id"],
    underHood: [
      "The route scopes its UPDATE by both user id and session id, preventing cross-account revocation.",
      "Session mode also deletes the Redis cache key so the revoked browser fails immediately.",
      "The response reports whether a matching session was actually revoked and records the action.",
    ],
  },
  {
    id: "revokeOthers",
    group: "Sessions",
    title: "Revoke other devices",
    method: "DELETE",
    path: "/users/me/sessions",
    summary: "Ends every session except the one making this request.",
    dangerous: true,
    underHood: [
      "The current refresh-token hash or session id is derived from the HTTP-only cookie.",
      "A database UPDATE invalidates every other matching row while preserving this browser's session.",
      "Redis cache entries are removed for server sessions and the exact revocation count is returned.",
    ],
  },
  {
    id: "password",
    group: "Security",
    title: "Change password",
    method: "PATCH",
    path: "/auth/password",
    summary: "Verifies the old password, stores a new hash, and signs out all devices.",
    fields: [field("old_password", "Current password", { type: "password" }), field("new_password", "New password", { type: "password" })],
    body: ["old_password", "new_password"],
    dangerous: true,
    refreshAuth: true,
    underHood: [
      "Argon2 first verifies the current password so a stolen unlocked session alone cannot silently change credentials.",
      "The new password is hashed with a fresh salt and committed to the database.",
      "All refresh tokens or sessions are revoked and cookies are cleared, requiring a clean login everywhere.",
    ],
  },
  {
    id: "twoFaSetup",
    group: "Security",
    title: "Prepare 2FA",
    method: "POST",
    path: "/auth/2fa/setup",
    summary: "Creates an encrypted TOTP secret and scannable authenticator QR code.",
    underHood: [
      "PyOTP creates a high-entropy base32 secret and a standards-compatible provisioning URI.",
      "The secret is encrypted with Fernet before storage; it is not enabled until a valid code confirms setup.",
      "The QR image is generated in memory and returned as a data URL for the browser to display.",
    ],
  },
  {
    id: "twoFaConfirm",
    group: "Security",
    title: "Confirm 2FA",
    method: "POST",
    path: "/auth/2fa/confirm",
    summary: "Verifies the first authenticator code and creates recovery codes.",
    fields: [field("secret_token", "6-digit authenticator code")],
    body: ["secret_token"],
    underHood: [
      "The encrypted secret is decrypted server-side and PyOTP verifies the current time window.",
      "Successful confirmation flips totp_enabled and generates ten one-time backup codes.",
      "Only hashes of backup codes are stored; the plaintext codes are returned once for safe offline storage.",
    ],
  },
  {
    id: "twoFaVerify",
    group: "Security",
    title: "Complete 2FA login",
    method: "POST",
    path: "/auth/2fa/verify",
    summary: "Exchanges the temporary login challenge and TOTP code for auth cookies.",
    fields: [field("user_id", "User id", { type: "number" }), field("temp_token", "Temporary token"), field("code", "Authenticator or backup code")],
    body: ["user_id", "temp_token", "code"],
    numeric: ["user_id"],
    refreshAuth: true,
    underHood: [
      "Redis validates the five-minute temporary token created after the password step and rate-limits failures.",
      "The code is checked as either a six-digit TOTP value or a one-time backup code whose hash is removed when used.",
      "Only after both factors pass does the selected backend issue the normal authenticated cookies.",
    ],
  },
  {
    id: "twoFaDisable",
    group: "Security",
    title: "Disable 2FA",
    method: "POST",
    path: "/auth/2fa/disable",
    summary: "Requires a current TOTP code before removing the second factor.",
    fields: [field("secret_token", "6-digit authenticator code")],
    body: ["secret_token"],
    dangerous: true,
    underHood: [
      "The backend refuses this action when 2FA is not active or the current authenticator code is invalid.",
      "A valid code clears the encrypted secret and all backup-code hashes in one transaction.",
      "The security timeline records the downgrade so the account owner can spot an unexpected change.",
    ],
  },
  {
    id: "backupCodes",
    group: "Security",
    title: "Rotate backup codes",
    method: "POST",
    path: "/users/me/backup-codes/regenerate",
    summary: "Invalidates every old recovery code and creates a fresh one-time set.",
    fields: [field("secret_token", "6-digit authenticator code")],
    body: ["secret_token"],
    dangerous: true,
    underHood: [
      "A live TOTP code re-authenticates the user before a sensitive recovery change.",
      "Ten random codes are generated; only SHA-derived hashes are retained in the account record.",
      "All previous backup codes stop working immediately and the plaintext replacements are returned once.",
    ],
  },
  {
    id: "adminUsers",
    group: "Administration",
    title: "List users",
    method: "GET",
    path: "/admin/users",
    summary: "Returns safe account records to administrators only.",
    underHood: [
      "The RoleChecker dependency authenticates the request and allows only the admin enum value.",
      "SQLAlchemy selects users and Pydantic filters each record through UserOut.",
      "Sensitive password, token, TOTP secret, and backup-code fields cannot enter the response.",
    ],
  },
  {
    id: "adminStats",
    group: "Administration",
    title: "Platform analytics",
    method: "GET",
    path: "/admin/stats",
    summary: "Returns high-level adoption and security counts for an admin dashboard.",
    underHood: [
      "An admin-only dependency runs before any aggregate query is allowed.",
      "SQL COUNT expressions calculate total, active, verified, 2FA-protected, and role distribution values.",
      "Only aggregate metrics are returned, making the response useful without exposing user details.",
    ],
  },
  {
    id: "adminRole",
    group: "Administration",
    title: "Change user role",
    method: "PATCH",
    path: "/admin/{u_id}/role",
    summary: "Assigns a validated user, moderator, or admin role.",
    fields: [field("u_id", "User id", { type: "number" }), field("role", "Role", { type: "select", options: ["user", "moderator", "admin"], defaultValue: "user" })],
    params: ["u_id"],
    body: ["role"],
    numeric: ["u_id"],
    underHood: [
      "The caller must pass the admin RoleChecker before FastAPI evaluates the target user.",
      "Pydantic constrains the role body to the RoleEnum values, preventing arbitrary privilege labels.",
      "SQLAlchemy updates the account and returns HTTP 404 when the target id does not exist.",
    ],
  },
  {
    id: "adminUnlock",
    group: "Administration",
    title: "Unlock account",
    method: "POST",
    path: "/admin/unlock/{username}",
    summary: "Clears a user's Redis failed-login counter.",
    fields: [field("username", "Username")],
    params: ["username"],
    underHood: [
      "The admin-only dependency prevents users from bypassing their own brute-force lockout.",
      "The username selects a namespaced Redis failed-attempt key rather than modifying account data.",
      "Deleting the counter allows the next legitimate password attempt to proceed immediately.",
    ],
  },
];

export const routeGroups = [...new Set(routeCatalog.map((route) => route.group))];

export function initialValues(route) {
  return Object.fromEntries(
    (route.fields || []).map((item) => [item.name, item.defaultValue || ""]),
  );
}
